services:
  mongo-reviews:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_review_data:/data/db

  mysql-lecture:
    image: mysql:latest
    ports:
      - 3308:3306
    volumes:
      - mysql_lecture_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  mysql-course:
    image: mysql:latest
    ports:
      - 3307:3306
    volumes:
      - mysql_course_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  review-service:
    depends_on:
      - mongo-reviews
    image: stijndb6/review-service:latest
    pull_policy: always
    ports:
      - 8082:8082
    links:
      - mongo-reviews
    environment:
      MONGODB_PORT: 27017
      MONGODB_HOST: mongo-reviews

  course-service:
    depends_on:
      - mysql-course
    image: stijndb6/course-service:latest
    pull_policy: always
    ports:
      - 8081:8081
    links:
      - mysql-course
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-course
      MYSQL_DB_PORT: 3306

  lecture-service:
    depends_on:
      - review-service
      - course-service
    image: stijndb6/lecture-service:latest
    pull_policy: always
    ports:
      - 8080:8080
    links:
      - review-service
      - course-service
    environment:
      REVIEW_SERVICE_BASEURL: review-service:8082
      COURSE_SERVICE_BASEURL: course-service:8081
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-lecture
      MYSQL_DB_PORT: 3306

  api-gateway:
    depends_on:
      - review-service
      - lecture-service
    image: stijndb6/ede-api-gateway:latest
    pull_policy: always
    ports:
      - 8083:8083
    links:
      - review-service
      - lecture-service
    environment:
      REVIEW_SERVICE_BASEURL: review-service:8082
      LECTURE_SERVICE_BASEURL: lecture-service:8080
      COURSE_SERVICE_BASEURL: course-service:8081

volumes:
  mongodb_review_data:
  mysql_course_data:
  mysql_lecture_data:
