server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: TRACE

spring:
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

  cloud:
    gateway:
      redis-rate-limiter:
        default-replenish-rate: 10
        default-burst-capacity: 20
      routes:
        - id: lecture-service
          uri: http://${LECTURE_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/lectures
          filters:
            - SetPath=/api/lecture
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@remoteAddrKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20

        - id: lecture-service-all
          uri: http://${LECTURE_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/lectures/all
            - Method=GET
          filters:
            - SetPath=/api/lecture/all
            - name: RequestRateLimiter

        - id: review-service
          uri: http://${REVIEW_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/reviews
            - Method=GET
          filters:
            - SetPath=/api/review/all
            - name: RequestRateLimiter

        - id: review-service-put
          uri: http://${REVIEW_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/reviews
            - Method=PUT
          filters:
            - SetPath=/api/review
            - name: RequestRateLimiter

        - id: course-service
          uri: http://${COURSE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/courses
            - Method=GET
          filters:
            - SetPath=/api/course/all
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@remoteAddrKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20