server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO

spring:
  cloud:
    gateway:
      routes:
        - id: lecture-service
          uri: http://${LECTURE_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/lectures
          filters:
            - SetPath=/api/lecture
        - id: lecture-service-all
          uri: http://${LECTURE_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/lectures/all
            - Method=GET
          filters:
            - SetPath=/api/lecture/all
        - id: review-service-get
          uri: http://${REVIEW_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/reviews
            - Method=GET
          filters:
            - SetPath=/api/review
        - id: review-service-put
          uri: http://${REVIEW_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/reviews
            - Method=PUT
          filters:
            - SetPath=/api/review
        - id: review-service-all
          uri: http://${REVIEW_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/reviews/all
            - Method=GET
          filters:
            - SetPath=/api/review/all
        - id: course-service
          uri: http://${COURSE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/courses
            - Method=GET
          filters:
            - SetPath=/api/course/all
